version: "3"

# This file is used for local development only. It is not used in production.

services:
  postgres:
    image: postgres:15
    command: '-d 1' # set debug-level
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
  redis:
    image: redis:latest
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "alembic upgrade head && pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"
    volumes:
      - ./app:/run/app
      - ./migrations:/run/migrations
      - ./.env:/run/.env # add local .env file to container
    ports:
      - "8000:8080"
      - "5678:5678"
    depends_on:
      - postgres
      - redis
    environment:
      - PYTHONDONTWRITEBYTECODE= # enable writing .pyc files for faster reloads
      - REDIS_CONNECTION_STRING=redis://redis:6379
      - POSTGRES_CONNECTION_STRING=postgresql+asyncpg://postgres:postgres@postgres:5432/main

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./.dev/pgadmin_servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  db_data:
  redis:
  pgadmin:
