FROM python:3.10 as requirements

ENV POETRY_VERSION=1.2.2

WORKDIR /tmp

RUN pip install "poetry==$POETRY_VERSION"

COPY poetry.lock pyproject.toml /tmp/

RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

FROM python:3.10-slim-bullseye

ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

RUN pip install --no-cache-dir --upgrade "uvicorn[standard]" gunicorn

COPY --from=requirements /tmp/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY gunicorn.conf.py /
COPY ./app /app

EXPOSE 8080

CMD ["gunicorn", "app.main:app", "--config=./gunicorn.conf.py", "--worker-class=uvicorn.workers.UvicornWorker", "--bind=0.0.0.0:8080"]
