"""Create Sample Table

Revision ID: 927c6a520d34
Revises:
Create Date: 2022-11-10 17:38:22.995342

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "927c6a520d34"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sample",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=10), nullable=True),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sample_id"), "sample", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sample_id"), table_name="sample")
    op.drop_table("sample")
    # ### end Alembic commands ###
